version: 2

aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v2-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

jobs:
  test-node-8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run:
          name: Install dependencies
          command: yarn --ignore-engines
      - save-cache: *save-cache
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Coverage report
          command: yarn test:report
      - store_test_results:
          path: test-results

  test-node-10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run:
          name: Install dependencies
          command: yarn --ignore-engines
      - save-cache: *save-cache
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Coverage report
          command: yarn test:report
      - store_test_results:
          path: test-results

  test-node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run:
          name: Install dependencies
          command: yarn --ignore-engines
      - save-cache: *save-cache
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Coverage report
          command: yarn test:report
      - store_test_results:
          path: test-results
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn install
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test-node-8
      - test-node-10
      - test-node-latest
      - release:
          requires:
            - test-node-8
            - test-node-10
            - test-node-latest
          filters:
            branches:
              only:
                - master
